### ISSUE TITLE
Pls upd react-easy-swipe

### ISSUE THREAD

**Issue by maxttor** [Middlerun/cheeseburger-menu#1]
Please update the package "react-easy-swipe" to new version. becouse your version throw a warning: 

> lowPriorityWarning.js?4545:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by Middlerun** [comment]
Done.
