### ISSUE TITLE
Are sub-menus supported?

### ISSUE THREAD

**Issue by kylesurowiec** [Middlerun/cheeseburger-menu#2]
Just curious if sub-menus are supported? I'd like to have a top level item possibly and then optionally expand it to reach its sub-pages.

**Comment by nemanjacosovic** [comment]
@kylesurowiec if you are thinking on sliding in additional off-canvas elements, no.

**Comment by kylesurowiec** [comment]
@nemanjacosovic Not what I was asking about but I will close the issue regardless.
